BEHEER_WACHTWOORD = "1234"
WINKEL_WACHTWOORD_FALLBACK = "winkel123"
SUPABASE_URL = "https://vuiidztqrmwoqwergurk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aWlkenRxcm13b3F3ZXJndXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NDkxNzksImV4cCI6MjEwMzQyNTE3OX0.ioolw5fVSWpC4KREhrTW0Pcqex4qEAUd8YEukVCtmrY"
